# Generated by Django 5.1.2 on 2024-10-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0002_alter_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
