# Generated by Django 5.1.2 on 2024-10-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0003_job_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='status',
            new_name='job_status',
        ),
    ]
