# Generated by Django 5.1.2 on 2024-10-29 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_alter_branch_branch_type'),
        ('job_posts', '0004_rename_status_job_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(choices=[('No Degree', 'No Degree'), ('O Level', 'O Level'), ('High School Diploma', 'High School Diploma'), ('Bachelor’s Degree', 'Bachelor’s Degree'), ('Master’s Degree', 'Master’s Degree'), ('PhD or Doctorate', 'PhD or Doctorate')], default='No Degree', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full-time', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_level',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid-Senior Level', 'Mid-Senior Level'), ('Senior Level', 'Senior Level')], default='Entry Level', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_location', to='companies.branch'),
        ),
    ]
