# Generated by Django 5.1.2 on 2024-10-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0005_alter_job_education_alter_job_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
