# Generated by Django 5.1.3 on 2024-11-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0006_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
