# Generated by Django 5.1.2 on 2024-11-07 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_applicant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submitted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
