# Generated by Django 5.1.2 on 2024-10-18 20:07

import companies.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Companies-logos', validators=[companies.models.validate_logo_size], verbose_name='Logo')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('established', models.DateField(default=django.utils.timezone.now)),
                ('employees', models.IntegerField()),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('c_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo', models.CharField(max_length=255)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('headquarters', models.CharField(max_length=255)),
                ('founded_by', models.CharField(blank=True, max_length=255)),
                ('number_of_branches', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_info', to='companies.company')),
            ],
        ),
    ]
