# Generated by Django 5.1.2 on 2024-10-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_c_user_alter_company_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='founded_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='headquarters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='number_of_branches',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
