# Generated by Django 5.1.2 on 2024-10-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_companyinfo_ceo_companyinfo_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
    ]
