# Generated by Django 5.1.2 on 2024-10-25 09:44

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='company_owner',
            field=models.ImageField(blank=True, default='company-owner.jpg', upload_to='Company_info', validators=[companies.models.validate_logo_size]),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='company-logo.jpg', upload_to='Companies', validators=[companies.models.validate_logo_size], verbose_name='Logo'),
        ),
    ]
