# Generated by Django 5.1.2 on 2024-10-25 16:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companyinfo_company_owner_alter_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='company',
            name='established',
        ),
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='employees',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='established',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comp_info', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='number_of_branches',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
