# Generated by Django 5.1.2 on 2024-10-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companyinfo_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=150),
        ),
    ]
