# Generated by Django 5.1.2 on 2024-10-25 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_companyinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='opened_on',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(blank=True, default='default@example.com', max_length=150),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d')]),
        ),
    ]
