# Generated by Django 5.1.2 on 2024-10-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_branch_opened_on_alter_companyinfo_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='opened_on',
            field=models.DateField(),
        ),
    ]
