# Generated by Django 5.1.2 on 2024-10-25 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_branch_opened_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='opened_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
