# Generated by Django 5.1.2 on 2024-10-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_branch_opened_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='employees',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='number_of_branches',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
