# Generated by Django 5.1.2 on 2024-10-29 13:32

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_companyinfo_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_image',
            field=models.ImageField(blank=True, default='branch-image.jpg', upload_to='Branches/', validators=[companies.models.validate_logo_size]),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='company-logo.jpg', upload_to='Companies/', validators=[companies.models.validate_logo_size], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_owner',
            field=models.ImageField(blank=True, default='company-owner.jpg', upload_to='Company_info/', validators=[companies.models.validate_logo_size]),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_picture',
            field=models.ImageField(blank=True, default='employee-image.jpg', upload_to='Employees/', validators=[companies.models.validate_logo_size]),
        ),
    ]
