# Generated by Django 5.1.2 on 2024-10-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_alter_branch_branch_image_alter_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('head', 'Head Office'), ('branch', 'Branch Office'), ('franchise', 'Franchise')], default='head', max_length=30),
        ),
    ]
