# Generated by Django 5.1.2 on 2024-10-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_branch_branch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('head', 'Head Office'), ('branch', 'Branch Office'), ('franchise', 'Franchise')], default='branch', max_length=30),
        ),
    ]
