# Generated by Django 5.1.2 on 2024-10-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_alter_branch_branch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('Head Office', 'Head Office'), ('Branch Office', 'Branch Office'), ('Franchise', 'Franchise')], default='Head Office', max_length=30),
        ),
    ]
