# Generated by Django 5.1.3 on 2024-11-08 22:44

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_alter_branch_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='country',
            field=django_countries.fields.CountryField(default='RW', max_length=2),
        ),
    ]
