# Generated by Django 5.1.3 on 2024-11-18 15:32

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_employee_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_image',
            field=models.ImageField(blank=True, upload_to='Branches/', validators=[companies.models.validate_logo_size]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('Head Office', 'Head Office'), ('Branch Office', 'Branch Office'), ('Franchise', 'Franchise')], max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='Companies/', validators=[companies.models.validate_logo_size], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_owner',
            field=models.ImageField(blank=True, upload_to='Company_info/', validators=[companies.models.validate_logo_size]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_picture',
            field=models.ImageField(blank=True, upload_to='Employees/', validators=[companies.models.validate_logo_size]),
        ),
    ]
