# Generated by Django 5.1.3 on 2024-11-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_alter_branch_branch_image_alter_branch_branch_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.CharField(default='Gicumbi', max_length=50),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
