# Generated by Django 5.1.3 on 2024-11-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_branch_location_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
