# Generated by Django 5.1.3 on 2024-11-18 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_alter_branch_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='opened_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='headquarters',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
