# Generated by Django 5.1.3 on 2024-11-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_alter_branch_opened_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='headquarters',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
